AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
 BucketName:
   Type: AWS::S3::Bucket
   Properties:
     BucketName: your-bucket-name
     AccessControl: PublicRead
     WebsiteConfiguration:
       IndexDocument: index.html
       ErrorDocument: error.html
     Policy:
       Version: '2012-10-17'
       Statement:
         - Effect: Allow
           Principal: '*'
           Action:
             - s3:GetObject
           Resource:
             - !Sub 'arn:aws:s3:::spin-fe-stage/*'